### PR TITLE
Move Flux tracing to utils class

### PR DESCRIPTION
**Pull request by Morlack**
Any reactor calls in the body of the TracingQueryGateway class will lead to a ClassNotFoundException upon boot of the application. The JVM will read the class, encounter a project reactor class and break.

This PR will remove this dependency in the body of the class and move it to a class that is not inspected using reflection: The SpanUtils

### CODE REVIEW

**Review by gklijs — APPROVED** [review]
Would be nice to add a test, but that needs another module, so it's quite a hassle. Looks good otherwise, although I noticed coverage is not measured, and therefore sonar fails.

**Review by schananas — APPROVED** [review]
looks good!

**Comment by Morlack** [comment]
> Would be nice to add a test, but that needs another module, so it's quite a hassle. Looks good otherwise, although I noticed coverage is not measured, and therefore sonar fails.

Yeah you are right, @gklijs. I had to test it locally by including it in a reactor-less project. Seems too much of a hassle to include a reactorless module like in the framework. If we still want that, it can be done.

**Review by smcvb — APPROVED** [review]
I don't think it's necessarily justified for this project to add a `reactorless-test` module purely for this. So, let's trust in your local-testing skills, @Morlack.

**Pull request merged**
