### PR TITLE
[#20] Support opentracing-api 0.33.0

### LINKED ISSUE #20: Support opentracing-api 0.33.0
For the moment the library is compatible with opentracing-api 0.31.0. Version 0.33.0 introduces non-backward compatible changes.

The extension must be reworked to use new opentracing API.

### PR DESCRIPTION
**Pull request by ghilainm**
This pull request resolves #20

### CODE REVIEW

**Comment by tomdevroomen** [comment]
Can this be merged and released?
It would help use greatly to extend our tracing!

Thnx!

**Comment by smcvb** [comment]
Good point @tomdevroomen, this should be merged somewhere soon. Pushing release through comments however doesn't work ;-)
@ghilainm, are you up to fix the merge conflicts in this PR?

**Comment by ghilainm** [comment]
@smcvb Done.

**Comment by smcvb** [comment]
@ghilainm, was it intentional to add those Gradle specific files?

**Comment by ghilainm** [comment]
@smcvb Not at all sorry for that, I am used to build with Gradle and didn't see I add those files :).

**Comment by tomdevroomen** [comment]
Thanks guys for the effort!

**Pull request merged**
